# -*- coding: utf-8 -*-
"""COD_PIXTRACT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VkUimzrygfVutSHmzMB_1pCuclEMJHeJ

Instalari
"""

from google.colab import drive
drive.mount('/content/drive')

from huggingface_hub import login
login("")

try:
    import qwen_vl_utils
except ImportError:
    !pip install qwen-vl-utils
#python-multipart e obligatoriu pentru FastAPI sa poata primi fisiere. Fara el, upload ul de imagine nu functioneaza
!pip install fastapi uvicorn pyngrok python-multipart pillow -q

""" Incarcare model"""

from transformers import Qwen2_5_VLForConditionalGeneration, AutoProcessor
from qwen_vl_utils import process_vision_info
import torch

print("Incarcare model...")
model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2.5-VL-7B-Instruct",
    # reducerea memoriei GPU la jumatate fata de float32, fara pierdere semnificativa de calitate.
    torch_dtype=torch.bfloat16,
    device_map="auto",
)
processor = AutoProcessor.from_pretrained("Qwen/Qwen2.5-VL-7B-Instruct")
print("Model incarcat!")

"""Schema + Rules"""

# CULORI

CULORI_BAZA = [
    "Alb", "Negru", "Gri", "Bej", "Crem", "Maro",
    "Rosu", "Roz", "Portocaliu", "Galben",
    "Verde", "Albastru", "Mov",
    "Multicolor", "Argintiu", "Auriu"
]

NUANTE = {
    "Gri":      ["Gri inchis", "Gri deschis"],
    "Maro":     ["Maro deschis", "Maro inchis"],
    "Rosu":     ["Burgundy", "Coral"],
    "Roz":      ["Roz pudra", "Fuchsia"],
    "Galben":   ["Galben mustar"],
    "Verde":    ["Verde militar", "Kaki", "Olive", "Verde menta", "Verde smarald"],
    "Albastru": ["Bleumarin", "Albastru royal", "Turcoaz", "Albastru deschis"],
    "Mov":      ["Lila", "Lavanda", "Pruna"]
}


# SCHEMA

SCHEMA = {
    "Tricouri dama": {
        "Imprimeu": ['Abstract','Animal print','Buline','Paiete','Dungi','Floral','Geometric','Grafic','Logo','Text','Tropical','Uni'],
        "Tip decolteu": ['Rotund','In V','Polo','Barcuta','Patrat','Cu umerii goi','Pe gat'],
        "Lungime maneca": ['Fara maneca','Scurta','Medie','Lunga'],
        "Culoare de baza": CULORI_BAZA,
        "Nuanta": NUANTE,
        "Croiala": ['Crop top','Regular fit','Slim fit','Oversized','Longline'],
        "Pentru": ['Femei']
    },
    "Tricouri barbati": {
        "Imprimeu": ['Abstract','Animal print','Camuflaj','Dungi','Floral','Geometric','Grafic','Logo','Text','Uni'],
        "Tip decolteu": ['In V','Polo','Rotund','Henley'],
        "Lungime maneca": ['Fara maneca','Scurta','Medie','Lunga'],
        "Culoare de baza": CULORI_BAZA,
        "Nuanta": NUANTE,
        "Croiala": ['Slim fit','Regular fit','Relaxed fit','Oversized','Longline'],
        "Pentru": ['Barbati']
    },
    "Tricouri copii": {
        "Imprimeu": ['Abstract','Animale','Animal print','Aplicatii decorative','Buline','Geometric','Desene animate','Dungi','Floral','Fructe','Grafic','Logo','Paiete','Text','Uni'],
        "Poveste/Personaj": ["Avengers","Barbie","Batman","Bluey","Cars","Disney Princess","Frozen","Garfield","Harry Potter","Hello Kitty","LOL Surprise","Mickey Mouse","Minnie Mouse","Minecraft","Minions","Miraculous Ladybug","Ninjago","Paw Patrol","PJ Masks","Popeye","Snoopy","Spider-Man","Sponge Bob","Star Wars","Superman","Tom & Jerry","Unicorn","Winnie the Pooh","Fara"],
        "Culoare de baza": CULORI_BAZA,
        "Nuanta": NUANTE,
        "Pentru": ['Baieti','Fete']
    },
    "Bluze dama": {
        "Imprimeu": ['Abstract','Animal print','Animale','Aplicatii decorative','Broderie','Buline','Camuflaj','Carouri','Dungi','Floral','Geometric','Grafic','Logo','Text','Tie-dye','Traditional','Tropical','Uni'],
        "Lungime maneca": ['Fara maneca','Scurta','Medie','Trei sferturi','Lunga'],
        "Culoare de baza": CULORI_BAZA,
        "Nuanta": NUANTE,
        "Croiala": ['Asimetric','Crop','Evazat','Oversized','Regular fit','Slim fit'],
        "Sistem inchidere": ['Capse','Fara inchidere','Fermoar','Nasturi','Snur','Funda'],
        "Pentru": ['Femei']
    },
    "Sandale dama": {
        "Culoare de baza": CULORI_BAZA,
        "Nuanta": NUANTE,
        "Tip": ['Sandale cu talpa joasa','Sandale cu platforma','Sandale cu toc','Sandale slingback','Sandale gladiator'],
        "Tip toc": ['Fara toc','Stiletto','Toc gros','Toc kitten','Platforma'],
        "Sistem inchidere": ['Catarama','Fara inchidere','Fermoar','Siret','Velcro'],
        "Pentru": ['Femei']
    },
    "Pantaloni sport barbati": {
        "Imprimeu": ['Uni','Logo','Grafic','Camuflaj','Dungi'],
        "Culoare de baza": CULORI_BAZA,
        "Nuanta": NUANTE,
        "Tip produs": ['Colanti','Pantaloni ski','Pantaloni de trening','Joggers'],
        "Lungime": ['Lungi','Scurti','Trei sferturi'],
        "Pentru": ['Barbati']
    }
}

# GLOBAL_RULES si COLOR_RULES merg in system prompt — se citesc o singura data indiferent de categorie
# RULES
GLOBAL_RULES = """
One image only. Analyze carefully before deciding.
- Not visible → null
- Never guess
- Ignore background and other objects
- Return ONLY valid JSON. No explanations.
- Each field: exactly ONE string or null. No arrays.
- Use ONLY exact values from schema (case-sensitive)
"""

COLOR_RULES = """
"Culoare de baza":
- Choose dominant color of the item only
- Ignore pattern colors, background, lighting
- Multiple strong colors → Multicolor
- Unclear → null

"Nuanta":
- Only attempt if base color is one of: Gri, Maro, Rosu, Roz, Galben, Verde, Albastru, Mov
- Otherwise → null immediately
- Choose closest shade only if clearly visible
- If unsure → null
- Never invent shade names
"""

RULES_TRICOURI_DAMA="""
You analyze women's t-shirts on a Romanian e-commerce platform.

- "Imprimeu": Look carefully at the surface pattern of the t-shirt
  * Abstract = irregular color splashes, paint-like effects,
  tie-dye, gradient blobs; NO clear recognizable shapes
  * Animal print = Mimics animal skins (leopard, zebra)
  * Buline = Repeated circles or dots
  * Camuflaj = Organic mottled military patterns
  * Paiete = Shiny, reflective disks/texture
  * Dungi = Parallel lines (any direction)
  * Floral = Flowers, buds, or bouquets
  * Geometric = Repeating shapes (triangles, squares, grids). A single geometric shape or artistic composition → Grafic, not Geometric.
  * Logo = Brand emblems or trademarks
  * Tropical = large exotic leaves, palm trees, jungle plants; NO cultural element
  * Text = Words, phrases, or typography
  * Uni = Single, solid color; no pattern
  * Desene animate = cartoon-style art featuring recognizable franchise
  characters (Mickey Mouse, Spider-Man, Frozen etc.)
  * Grafic = any bold visual design that does NOT fit other categories:
  illustrations, drawings, pop-art, portraits, landscapes,
  photographic prints, animals drawn in artistic style,
  cartoon characters on adult clothing,
  single large artistic composition (NOT a repeating pattern).
  NOT Uni, NOT Logo, NOT Text, NOT Floral, NOT Animal print,
  NOT Dungi, NOT Buline, NOT Geometric (repeating pattern),
  NOT Abstract (shapeless splashes).
  Grafic has clear recognizable shapes or figures.
  When in doubt → choose the more specific category first.
  Grafic is the fallback for any clear visual design with no better match.


- "Tip decolteu": Look carefully at the neckline of the t-shirt
  * Rotund = Circular curve at neck base
  * In V = Dips to a sharp "V" point
  * Polo = Collar with a short button placket
  * Barcuta = Wide, horizontal line across collarbones
  * Patrat = Rectangular shape with three straight edges
  * Cu umerii goi = Sits below shoulders; exposed collarbones
  * Pe gat = Fabric covers part/all of the neck
  IMPORTANT:
  - If you can see ANY neckline at all, you MUST return one value
  - Only return null if the neckline is 100% invisible

- "Croiala": Look carefully at the overall fit and proportions of the t-shirt
  * Crop = Very short body; height is similar to or less than width
  * Regular fit = Straight cut; standard proportions (ends at hip level)
  * Slim fit = Narrow waist; fabric looks contoured or tight
  * Oversized = Very wide body and dropped shoulders; boxy shape
  * Longline = Significantly elongated body; much longer than a standard tee

- "Lungime maneca": Look carefully at the sleeve length of the t-shirt
  * Fara maneca = No sleeves; shoulder is exposed or capped
  * Scurta = Ends between shoulder and mid-bicep
  * Medie = Ends at or near the elbow
  * Lunga = Extends to the wrist or covers the hand

- "Pentru": always write "Femei"
"""


RULES_TRICOURI_BARBATI = """
You analyze men's t-shirts on a Romanian e-commerce platform.

- "Imprimeu": Look carefully at the surface pattern of the t-shirt
  * Abstract = irregular color splashes, paint-like effects,
  * Animal print = Mimics animal skins (leopard, zebra)
  * Camuflaj = Organic mottled military patterns
  * Dungi = Parallel lines (any direction)
  * Floral = Flowers, buds, or bouquets
  * Geometric = Repeating shapes (triangles, squares, grids). A single geometric shape or artistic composition → Grafic, not Geometric.
  * Logo = Brand emblems or trademarks
  * Text = Words, phrases, or typography
  * Uni = Single, solid color; no pattern
  * Grafic = any bold visual design that does NOT fit other categories:
  illustrations, drawings, pop-art, portraits, landscapes,
  animals drawn in artistic style, cartoon characters and franchise
  characters (Mickey Mouse, Spider-Man etc.) when they appear on
  adult clothing, abstract compositions with clear shapes.
  NOT Uni, NOT Logo, NOT Text, NOT Floral, NOT Animal print, NOT Dungi.
  When in doubt → choose the more specific category first.
  Grafic is the fallback for any clear visual design with no better match.

- "Tip decolteu": Look carefully at the neckline of the t-shirt
  * In V = Dips to a sharp "V" point
  * Polo = Structured collar with a partial button placket
  * Rotund = Circular curve at the base of the neck (Crew neck)
  * Henley = Round neckline with a partial button placket (like a Polo, but WITHOUT the collar)
  IMPORTANT:
  - Polo = Has a collar + buttons
  - Henley = NO collar + buttons

- "Lungime maneca": Look carefully at the sleeve length of the t-shirt
  * Fara maneca = No sleeves; shoulder is exposed or capped
  * Scurta = Ends between shoulder and mid-bicep
  * Medie = Ends at or near the elbow (3/4 length included)
  * Lunga = Extends to the wrist or covers the hand

- "Croiala": Look at proportions and seams (applies to both human models and flat-lays)
  * Slim fit = Narrow waist/torso; side seams are curved inwards; sleeves look tight
  * Regular fit = Straight side seams; standard width-to-height ratio
  * Relaxed fit = Wider body than regular, but the shoulder-to-sleeve seam stays at the edge of the shoulder
  * Oversized = Very wide "boxy" body; dropped shoulders (the sleeve seam starts much lower than the actual shoulder corner)
  * Longline = Body is unusually long compared to its width; t-shirt is elongated
IMPORTANT:
- Choose the closest matching fit based on visible proportions
- If the fit is unclear or hidden → return null
- Return ONLY ONE value

- "Pentru": always "Barbati"
"""


RULES_TRICOURI_COPII = """
You analyze children's t-shirts on a Romanian e-commerce platform

- "Pentru":
  * Baieti = boys clothing; often includes themes like superheroes, cars, sports, dinosaurs
  * Fete = girls clothing; often includes themes like princesses, dolls, glitter, flowers

  IMPORTANT:
  - If clearly targeted → choose value. If unclear → null
  - Clearly boy theme → Baieti
  - Clearly girl theme → Fete

- "Imprimeu": Look carefully at the surface pattern of the t-shirt.
  * Abstract = irregular color splashes, paint-like effects
  * Animal print = Patterns that mimic animal skin (leopard, zebra, snake).
  * Animale = Illustrations or images of real animals (dogs, cats, birds, etc).
  * Aplicatii decorative = 3D attachments like beads, pearls, or studs
  * Buline = Polka dots
  * Desene animate = Characters from movies, comics, or TV shows (e.g., Mickey Mouse, Anime, etc).
  * Geometric = Repeating shapes (triangles, squares, grids). A single geometric shape or artistic composition → Grafic, not Geometric.
  * Dungi = Horizontal, vertical, or diagonal stripes.
  * Floral = Flower, leaf, or botanical patterns.
  * Fructe = Prints featuring fruits (lemons, cherries, etc.)
  * Logo = Visible brand symbols or brand names
  * Paiete = Shiny, reflective sequins or glittery scales
  * Text = Words, slogans, or repeated typography
  * Uni = Solid, single color with no pattern
  * Grafic = any bold visual design that does NOT fit other categories:
  includes illustrations, drawings, pop-art, portraits, landscapes,
  animals drawn in artistic style, abstract compositions with clear shapes,
  cartoon-style art WITHOUT recognizable franchise characters,
  geometric art that tells a story or has a theme.
  NOT Uni, NOT Logo, NOT Text, NOT Floral, NOT Animal print, NOT Dungi, NOT Buline, NOT Geometric.
  When in doubt between Grafic and another category → choose the more specific one.
  Grafic is the fallback for any clear visual design that has no better match.

  IMPORTANT:
  - Choose the DOMINANT visual element
  - If multiple patterns exist → choose the most visible one
  - If pattern is unclear → return null
  - Return ONLY ONE value


- "Poveste/Personaj": Identify the specific character or franchise shown on the t-shirt
  * Avengers = Marvel superhero group
  * Barbie = Fashion doll themes/logos
  * Batman = DC superhero / bat logo
  * Bluey = Australian cattle dog characters
  * Cars = Lightning McQueen / racing vehicles
  * Disney Princess = Cinderella, Belle, Ariel, etc
  * Frozen = Anna, Elsa, Olaf
  * Garfield = Orange tabby cat
  * Harry Potter = Hogwarts, wizarding world motifs
  * Hello Kitty = Sanrio cat with bow
  * LOL Surprise = Collectible doll characters
  * Mickey Mouse = Classic Disney male mouse
  * Minnie Mouse = Classic Disney female mouse
  * Minecraft = Blocky/pixelated game elements
  * Minions = Yellow Gru’s henchmen
  * Miraculous Ladybug = Marinette / Ladybug characters
  * Ninjago = Lego ninja characters
  * Paw Patrol = Rescue dogs (Chase, Marshall, etc.)
  * PJ Masks = Catboy, Owlette, Gekko
  * Popeye = Sailor man / spinach motifs
  * Snoopy = Peanuts beagle dog
  * Spider-Man = Web motifs / red-blue suit
  * Sponge Bob = SquarePants / Bikini Bottom
  * Star Wars = Jedi, Vader, Stormtroopers
  * Superman = Man of Steel / “S” shield
  * Tom & Jerry = Classic cat and mouse duo
  * Winnie the Pooh = Hundred Acre Wood characters
  * Fara = No specific character
  IMPORTANT:
  - Use this field ONLY if "Imprimeu" = "Desene animate"
  - If "Imprimeu" is  not "Desene animate" → return null
  - If a character is clearly recognizable → return exact value
  - If cartoon style but NO specific character → return null
  - If unclear → return null
  - Return ONLY ONE value
"""

RULES_BLUZE_DAMA = """
You analyze women's blouses on a Romanian e-commerce platform.

- "Imprimeu": Pattern detection rules:
  * Abstract: non-geometric, random artistic shapes/splashes
  * Animal print: animal skin textures (leopard/zebra)
  * Animale: real animals (drawings or photos; NOT abstract shapes)
  * Aplicatii decorative: 3D elements (beads/pearls/lace)
  * Broderie: stitched thread patterns
  * Buline: polka dots
  * Camuflaj: military camo patches
  * Carouri: plaid/checkered/grid patterns
  * Dungi: stripes
  * Floral: flowers/petals/botanical patterns
  * Geometric: repeating structured shapes (triangles/hexagons/grids)
  * Grafic: digital or abstract art (NO characters, NO faces, NO animals)
  * Logo: brand name or emblem
  * Text: words/slogans/letters
  * Tie-dye: blurred/washed spiral color effects
  * Uni: solid color, no print
  IMPORTANT:
  - Choose the MOST visible pattern (dominant)
  - If multiple patterns exist → pick the dominant one
  - Small details (e.g., small logo/text) → Uni
  - If unclear → return null
  - Return ONLY ONE value

- "Lungime maneca": Arm coverage detection:
  * Fara maneca: No sleeves; shoulders fully exposed
  * Scurta: Ends above the elbow (upper arm)
  * Medie: Ends at or near the elbow
  * Trei sferturi: Ends between elbow and wrist (mid-forearm)
  * Lunga: Extends to the wrist or covers part of the hand
  IMPORTANT:
  - Focus ONLY on the sleeve length of the t-shirt
  - Ignore rolled or folded sleeves
  - If sleeve length is unclear → return null
  - Return ONLY ONE value

- "Croiala": Silhouette and fit detection:
  * Asimetric: Uneven hemline or irregular proportions
  * Crop: Square/short ratio; width is similar to or greater than length
  * Evazat: Flared or wider towards the bottom
  * Oversized: Very loose, baggy, or intentionally large; may have dropped shoulders
  * Regular fit: Standard straight cut; not tight, not loose
  * Slim fit: Form-fitting; follows the body closely
  IMPORTANT:
  - Focus on overall silhouette (width, length, and shape)
  - If multiple fits seem possible → choose the closest match
  - Prioritize clear visual cues:
    - very short → Crop
    - very loose → Oversized
    - flared bottom → Evazat
    - tight → Slim fit
    - otherwise → Regular fit
  - If fit is unclear → return null
  - Return ONLY ONE value

- "Sistem inchidere": Fastening detection:
  * Capse: Small snap-on metal/plastic studs
  * Fara inchidere: One-piece item, slips over the head
  * Fermoar: Metallic/nylon zipper teeth
  * Nasturi: Classic round buttons along the front or back.
  * Snur: Thin adjustable cords (often at neckline or waist)
  * Funda: Fabric ribbons tied in a bow (functional or decorative)
Critical points for the model:
- If the blouse has buttons only on the cuffs but is worn over the head, set "Fara inchidere"
- Bows are often located at the back (neck) or at the neckline

- "Pentru": always "Femei"
"""

RULES_SANDALE = """
You analyze women's sandals on a Romanian e-commerce platform

- "Tip": Sandal style detection:
  * Sandale cu talpa joasa: Flat sole; no elevation or heel
  * Sandale cu platforma: Thick, continuous high sole (front to back)
  * Sandale cu toc: Distinct raised heel (block, stiletto, or kitten)
  * Sandale slingback: Open heel with a strap around the back
  * Sandale gladiator: Multiple straps wrapping up the foot/ankle/leg
Key points for the model:
- Slingback vs Gladiator:
  If it has a single strap at the heel → Slingback
  If it has multiple straps going up the foot/leg → Gladiator
- Platform vs Toc:
  If the sole is thick also under the toes (not just at the heel) → prioritize Platform
- If unclear → null

- "Tip toc": Specific heel shape detection:
  * Fara toc: Completely flat sole
  * Stiletto: Tall, very thin, needle-like heel; clearly longer than it is wide
  * Toc gros: Wide, chunky block heel for stability
  * Toc kitten: Very small, thin heel; looks like a tiny stub; height is similar to its width
  * Platforma: Thick sole under the entire foot(not just at the heel)
  IMPORTANT:
  - If heel is NOT clearly visible → return null
  - DO NOT guess

- "Sistem inchidere":
  * Catarama: Buckle with a strap (metal/plastic closure)
  * Fara inchidere: Slip-on; no visible fastening mechanism
  * Fermoar: Zipper (usually at the back or side)
  * Siret: Cords or laces tied in a knot or bow
  * Velcro: Overlapping straps that stick together; look for a blunt strap end (no pin) pressed onto another surface
  IMPORTANT:
  - Analyze ONLY the sandal (ignore other objects)
  - Choose the MAIN visible fastening mechanism
  - If multiple exist → prioritize the most functional one
  - If no fastening is visible → Fara inchidere

- "Pentru": Always "Femei"
"""

RULES_PANTALONI = """
You analyze men's sports pants on a Romanian e-commerce platform

- "Imprimeu": Surface pattern detection:
  * Uni: Solid, single color; no visible patterns (small logo does NOT count).
  * Logo: Large, clearly visible brand symbol or name
  * Grafic: Bold digital prints or artistic designs (NO logos)
  * Camuflaj: Military-style patches (green, grey, or earth tones)
  * Dungi: Vertical or horizontal stripes
  IMPORTANT:
  - Analyze ONLY the pants (ignore t-shirt or other clothing items)
  - Choose the MOST visible pattern
  - Small logo → Uni
  - If multiple patterns exist → pick the dominant one
  - If unclear → return null
  - Return ONLY ONE value

- "Tip produs": Silhouette and material detection:
  * Colanti: Skin-tight; fabric follows the leg completely; no loose areas
  * Pantaloni ski: Thick, bulky; waterproof or insulated; often padded
  * Pantaloni de trening: Loose or straight fit; soft jersey/fleece fabri
  * Joggers: Tapered legs with elastic or ribbed cuffs at the ankles
  IMPORTANT:
  - Analyze ONLY the pants (ignore other clothing items)
  - Focus on fit + material + leg shape
  - Prioritize clear visual cues:
    - skin-tight → Colanti
    - thick/padded → Pantaloni ski
    - loose + soft fabric → Pantaloni de trening
    - narrow leg + elastic cuffs → Joggers
  - If multiple seem possible → choose the closest match
  - If unclear → return null
  - Return ONLY ONE value

- "Lungime": Leg coverage detection:
  * Lungi: Full length; covers the ankles
  * Scurti: Ends above or at the knee
  * Trei sferturi: Ends below the knee, mid-calf
  IMPORTANT:
  - Analyze ONLY the pants (ignore other clothing items)
  - Focus on where the pant leg ENDS on the leg
  - If length is unclear → return null
  - Return ONLY ONE value

- "Pentru": always "Barbati"
"""

#dict care leaga numele categoriei de regulile ei; cand vine request ul cu "categorie": "Tricouri dama", codul face RULES_MAP["Tricouri dama"] si gaseste prompt ul corect
RULES_MAP = {
    "Tricouri dama": RULES_TRICOURI_DAMA,
    "Tricouri barbati": RULES_TRICOURI_BARBATI,
    "Tricouri copii": RULES_TRICOURI_COPII,
    "Bluze dama": RULES_BLUZE_DAMA,
    "Sandale dama": RULES_SANDALE,
    "Pantaloni sport barbati": RULES_PANTALONI
}

""" Toate functiile"""

from PIL import Image
import io, base64, json, re, gc, torch


# IMAGINE
MAX_SIZE = (1024, 1024)

def prepare_image(image_bytes: bytes) -> str:
    img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    # Nu crop, nu stretch. Daca imaginea e 4000x3000, o face 1024x768 pastrand proportia; quality= 85 e echilibrul bun intre dimensiune si claritate pentru model
    img.thumbnail(MAX_SIZE, Image.LANCZOS)  # resize proportional, fara crop
    buffer = io.BytesIO()
    img.save(buffer, format="JPEG", quality=85)
    return base64.b64encode(buffer.getvalue()).decode("utf-8")


# PROMPT
#construieste textul final care merge la model: regulile categoriei + culorile permise + nuantele; asta e ce vede modelul ca "user message".
def build_prompt(categorie: str) -> str:
    rule = RULES_MAP.get(categorie)
    if not rule:
        raise ValueError(f"Categorie necunoscuta: {categorie}")

    schema = SCHEMA[categorie]
    culori = schema["Culoare de baza"]
    nuante = {k: v for k, v in NUANTE.items()}

    return (
        f"{rule}\n\n"
        f"Allowed colors: {culori}\n"
        f"Shades per color: {nuante}\n\n"
        f"Return ONLY a valid JSON object. No extra text."
    )


# PARSARE
def parse_json(text: str) -> dict:
    try:
        return json.loads(text)
    except:
        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except:
                pass
    return None


# NORMALIZARE
def normalize_color(data: dict) -> dict:
    baza = data.get("Culoare de baza")
    nuanta = data.get("Nuanta")

    if not baza or baza not in NUANTE:
        data["Nuanta"] = None
        return data

    if not nuanta or nuanta not in NUANTE[baza]:
        data["Nuanta"] = None

    return data

# curata ce returneaza modelul
# 3 lucruri face: scoate ':' de la sfarsitul cheilor, daca returneaza o lista ia primul element si aplica logica de nuanta
def normalize_output(data: dict, categorie: str) -> dict:
    if not data:
        return None

    # curata chei cu ':' la final- e posibil sa puna el un ':'
    data = {k.strip().rstrip(":").strip(): v for k, v in data.items()}

    # daca valoare e lista, ia primul element
    data = {
        k: (v[0] if isinstance(v, list) and v else v)
        for k, v in data.items()
    }

    data = normalize_color(data)

    if "Poveste/Personaj" in data:
        if data.get("Imprimeu") != "Desene animate":
            data["Poveste/Personaj"] = None

    return data


# MODEL CALL
#construieste mesajele in formatul cerut de Qwen, tokenizeaza, genereaza, decodifica; max_new_tokens=256 e suficient pentru un JSON mic. do_sample=False +
# + temperature=0.1 il face cat mai determinist — vrei acelasi raspuns la aceeasi imagine
def run_qwen(image_base64: str, categorie: str) -> dict:
    system_prompt = GLOBAL_RULES + COLOR_RULES
    user_prompt = build_prompt(categorie)

    messages = [
        {
            "role": "system",
            "content": system_prompt
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "image": f"data:image/jpeg;base64,{image_base64}"
                },
                {
                    "type": "text",
                    "text": user_prompt
                }
            ]
        }
    ]

    text = processor.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    image_inputs, video_inputs = process_vision_info(messages)
    inputs = processor(
        text=[text],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt"
    ).to(model.device)

    with torch.no_grad():
        generated_ids = model.generate(
            **inputs,
            max_new_tokens=256,
            temperature=0.1,
            do_sample=False
        )

    generated_ids_trimmed = [
        out_ids[len(in_ids):]
        for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
    ]
    output_text = processor.batch_decode(
        generated_ids_trimmed,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False
    )[0]

    gc.collect()
    torch.cuda.empty_cache()

    return parse_json(output_text)


# FUNCTIA PRINCIPALA
def extract_attributes(image_bytes: bytes, categorie: str) -> dict:
    image_base64 = prepare_image(image_bytes)
    raw = run_qwen(image_base64, categorie)

    if not raw:
        return {"error": "JSON parse failed"}

    return normalize_output(raw, categorie)

def test_one_image(image_path: str, categorie: str):
    if categorie not in RULES_MAP:
        print(f"[ERROR] Categorie invalida: '{categorie}'")
        print(f"Categorii disponibile: {list(RULES_MAP.keys())}")
        return

    try:
        with open(image_path, "rb") as f:
            image_bytes = f.read()
    except FileNotFoundError:
        print(f"[ERROR] Fisierul nu a fost gasit: {image_path}")
        return

    print(f"[INFO] Procesez imaginea: {image_path}")
    print(f"[INFO] Categorie: {categorie}\n")

    result = extract_attributes(image_bytes, categorie)
    print(json.dumps(result, ensure_ascii=False, indent=2))

test_one_image("", "")

"""FastAPI"""

from fastapi import FastAPI, UploadFile, File, Form
from fastapi.responses import JSONResponse
from datetime import datetime
import uuid
from pyngrok import ngrok

ngrok.set_auth_token("")

app = FastAPI()

@app.post("/extract")
async def extract(
    file: UploadFile = File(...),
    categorie: str = Form(...),
    product_id: str = Form(None)
):
    try:
        image_bytes = await file.read()

        if categorie not in RULES_MAP:
            return JSONResponse(status_code=400, content={
                "success": False,
                "error": f"Categorie invalida: {categorie}"
            })

        pid = product_id if product_id else f"P-{str(uuid.uuid4())[:6]}"

        result = extract_attributes(image_bytes, categorie)

        if "error" in result:
            return JSONResponse(status_code=500, content={
                "success": False,
                "error": result["error"]
            })

        return JSONResponse(content={
            "success": True,
            "productId": pid,
            "category": categorie,
            "processedAt": datetime.utcnow().isoformat(),
            "attributes": result
        })

    except Exception as e:
        return JSONResponse(status_code=500, content={
            "success": False,
            "error": str(e)
        })
# e o ruta simpla de verificare; cand pornesc Colab si vreau sa stiu daca serverul e activ, dau un GET la /health din browser sau Postman si imi returneaza {"status": "ok"}.
@app.get("/health")
async def health():
    return {"status": "ok", "model": "Qwen2.5-VL-7B"}

"""Pornire server"""

import threading
import uvicorn
import time
from pyngrok import ngrok

def run_server():
    uvicorn.run(app, host="0.0.0.0", port=8000)
#                                           dacă celula se oprește, se oprește și serverul.
thread = threading.Thread(target=run_server, daemon=True)
thread.start()

#e necesar ca serverul să pornească înainte să ceri URL-ul de la ngrok.
time.sleep(2)

public_url = ngrok.connect(8000)
print(f"\n API URL: {public_url}")
print(f" Health check: {public_url}/health")
print(f"\n Copiaza URL-ul de mai sus in appsettings.json din .NET")